steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sheersdigital-site:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sheersdigital-site:latest'
      - '.'
    id: 'build-image'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sheersdigital-site:$COMMIT_SHA'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sheersdigital-site:latest'
    id: 'push-image-latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sheersdigital-site'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sheersdigital-site:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
    id: 'deploy-cloud-run'

images:
  - 'gcr.io/$PROJECT_ID/sheersdigital-site:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sheersdigital-site:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

