apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheersdigital-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sheersdigital-site
  template:
    metadata:
      labels:
        app: sheersdigital-site
    spec:
      containers:
      - name: sheersdigital-site
        image: localhost:5000/sheersdigital-site:latest
        ports:
        - containerPort: 80